repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/JohnnyMorganz/StyLua
  rev: v0.14.2
  hooks:
    - id: stylua # or stylua-system / stylua-github
- repo: local
  hooks:
    - id: trufflehog
      name: TruffleHog
      description: Detect secrets in your data.
      entry: bash -c 'trufflehog-launcher git main HEAD'
      language: system
      stages: ["push"]
